# Generated by Django 4.2 on 2023-04-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentarios', '0001_initial'),
        ('avaliacoes', '0001_initial'),
        ('enderecos', '0001_initial'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('atracoes', models.ManyToManyField(to='atracoes.atracoes')),
                ('avalicao', models.ManyToManyField(to='avaliacoes.avaliacoes')),
                ('comentario', models.ManyToManyField(to='comentarios.comentarios')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.enderecos')),
            ],
        ),
    ]
